version: "3.9"

services:
  backend:
    build: ./backend
    container_name: node-backend
    restart: always
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    ports:
      - "3000:80"

  nginx:
    image: nginx:stable-alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
